# ===============================
# = SERVER
# ===============================
server:
  port: ${PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH:/api/v1/rooms}

# ===============================
# = LOGGING
# ===============================
logging:
  level:
    sk.janobono.sca.roomservice: ${LOG_LEVEL:debug}

spring:
  # ===============================
  # = APPLICATION
  # ===============================
  application:
    name: roomservice
  config:
    import: optional:configserver:http://localhost:9000/
  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/room_service}
    username: ${DB_USER:app}
    password: ${DB_PASS:app}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

# ===============================
# = EUREKA
# ===============================
eureka:
  client:
    service-url:
      defaultZone: ${EUREKASERVER:http://localhost:8761/eureka}
