# ===============================
# = SERVER
# ===============================
server:
  port: ${PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH:/api/v1/rooms}

# ===============================
# = LOGGING
# ===============================
logging:
  level:
    sk.janobono.sca.roomservice: ${LOG_LEVEL:debug}

spring:
  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/room_service?characterEncoding=UTF-8}
    username: ${DB_USER:app}
    password: ${DB_PASS:app}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

# ===============================
# = SPRING DOC
# ===============================
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
