# ===============================
# = SERVER
# ===============================
server:
  port: ${PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH:/api/v1/reservations}

# ===============================
# = LOGGING
# ===============================
logging:
  level:
    sk.janobono.sca.reservationservice: ${LOG_LEVEL:debug}

spring:
  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/reservation_service}
    username: ${DB_USER:app}
    password: ${DB_PASS:app}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
