# ===============================
# = SERVER
# ===============================
server:
  port: ${PORT:9000}

spring:
  cloud:
    config:
      server:
        git:
          uri: ${HOME}/workspace/simple-cloud-app-config
          force-pull: true
