# ===============================
# = SERVER
# ===============================
server:
  port: ${PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH:/api/v1/room-reservations}

# ===============================
# = LOGGING
# ===============================
logging:
  level:
    sk.janobono.sca.roomreservationservice: ${LOG_LEVEL:debug}

# ===============================
# = SPRING DOC
# ===============================
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

# ===============================
# = APP
# ===============================
app:
  customer-service-url: ${APP_CUSTOMER_SERVICE_URL:http://localhost:8800}
  reservation-service-url: ${APP_RESERVATION_SERVICE_URL:http://localhost:8801}
  room-service-url: ${APP_ROOM_SERVICE_URL:http://localhost:8802}
