version: '3.2'

services:
  mysql:
    image: mysql:8-debian
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
