version: '3.2'

services:
  mysql:
    image: mysql:8-debian
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql

  configserver:
    image: sk.janobono.sca/config-server:latest
    ports:
      - 9000:8080

  eurekaserver:
    image: sk.janobono.sca/eureka-server:latest
    ports:
      - 8761:8761

  customerservice:
    image: sk.janobono.sca/customer-service:latest
    restart: always
    ports:
      - 8800:8080
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://configserver:8080/
      - EUREKASERVER=http://eurekaserver:8761/eureka
    depends_on:
      - mysql
      - configserver
      - eurekaserver

  reservationservice:
    image: sk.janobono.sca/reservation-service:latest
    restart: always
    ports:
      - 8801:8080
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://configserver:8080/
      - EUREKASERVER=http://eurekaserver:8761/eureka
    depends_on:
      - mysql
      - configserver
      - eurekaserver

  roomservice:
    image: sk.janobono.sca/room-service:latest
    restart: always
    ports:
      - 8802:8080
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://configserver:8080/
      - EUREKASERVER=http://eurekaserver:8761/eureka
    depends_on:
      - mysql
      - configserver
      - eurekaserver

  roomreservationservice:
    image: sk.janobono.sca/room-reservation-service:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      - EUREKASERVER=http://eurekaserver:8761/eureka
    depends_on:
      - eurekaserver

volumes:
  mysql-data:
